### PR TITLE
Make project logo visible in GitHub dark mode

### PR DESCRIPTION
**Pull request by Andrew6rant**
Hacktoberfest 2021 entry.

This commit tweaks the logo of the GitHub README to be more visible in GitHub's dark mode.

Here are some comparison screenshots. Before:

before_dark

After:

after_dark

And there should be no difference in appearance for light mode. Before:

before_light

After:

after_light

### CODE REVIEW

**Comment by aUnicornDev** [comment]
Thanks a lot for your contribution. I will create an Issue for the dark mode logo. Can you convert this to dark mode logo as well and add it to this PR?

**Comment by Andrew6rant** [comment]
> Can you convert this to dark mode logo as well

I'm sorry, I am not exactly sure what you mean. What do you want me to convert?

**Comment by aUnicornDev** [comment]
In the logo svg, can we another svg with completely inverted colors .. so as to make a dark theme logo?.

**Review by aUnicornDev — APPROVED** [review]
The changes look good. Thank you for replacing the long URL with docs as well. Please feel free to contribute to the repo in the coming days.

**Comment by Andrew6rant** [comment]
Oh, I see. I've added an inverted colored "tabsMonster_dark.svg" to the repo, it looks like this:

image

I've also edited tabsMonster.png to work in both light and dark mode.

Before:

image

After:

image

The appearance is not changed on light mode.

**Pull request merged**
