### PR TITLE
Added Pokemon with quotes

### PR DESCRIPTION
**Pull request by Pranai2518**
Added pokemon theme#8

### CODE REVIEW

**Comment by Pranai2518** [comment]
Hi @aUnicornDev, What You are saying about N Pokemon Black/White character?

**Comment by Pranai2518** [comment]
So what about the pokemon theme that I have added you want me to delete or keep it.

**Comment by aUnicornDev** [comment]
Don't delete anything.. keep the old ones and the new ones.

**Comment by Pranai2518** [comment]
Check it now. As you said.

**Pull request merged**
